name: learn-github-actions
on: [push]
jobs:
  check-bats_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setupnode@v1
      - run: npm install -g bats
      - run: bats -v